### ISSUE TITLE
PDF manual needs to be replaced with the up-to-date (draft) version

### ISSUE THREAD

**Issue by magnusnissel** [magnusnissel/DEPiCTed#15]
The PDF file should be replaced with a more current version before releasing the "first" version to contributors.

**Comment by DamarisNeuhof** [comment]
I agree. 
Could you maybe already delete the source type list under "View manual" so that there is just the button "Open the Full DEPiCTed User Manual (PDF)"? I already inserted the source type list with explanations and examples into the User Manual and I think it will look nicer if there is just the button leading to the manual. If you could do that already I could make a screenshot and insert the correct screenshot in the manual before sending it to you.
In addition, I already updated most of the videos and only have two left. After that I will send the pre-final glossless Manual version to you (even though there might be still some changes when Viveka is back, as there are some minor things I have to discuss with her).

One thing we recognised is that the User Manual PDF to which the button leads does not look like my PDF. I am unsure why but unfortunately some things are shifted and the hyperlinks do not work neither. But maybe we can try it again with the new manual.

**Comment by magnusnissel** [comment]
Can do. Yeah it looks not like your PDF because I only had an (old) Word version of the manual and simply used "Export to PDF". I assume that is where the differences came from.

**Comment by magnusnissel** [comment]
Closed.
